spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hackatum?serverTimezone=Europe/Berlin
        username: hackatum3
        password: Challenge.2022
        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        enabled: true

server.port: 8080
