spring:
    datasource:
        url: jdbc:h2:./.h2_db/hackatum;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=true
        username: hackatum
        password: challenge
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
